export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_IN_WITH_EMAIL_START: "SIGN_IN_WITH_EMAIL_START",
  GOOGLE_SIGN_IN_EMAIL_START: "GOOGLE_SIGN_IN_EMAIL_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
};
